app_racine/mosque/__init__.py
from flask import Blueprint

mosque_bp = Blueprint('mosque_bp', __name__, url_prefix="/mosque")

from app_racine.mosque import models, routes

app_racine/mosque/routes.py
import secrets
from app_racine.mosque import mosque_bp

from app_racine.mosque.forms import *

from app_racine.donors.models import *

from app_racine.authentication.forms import *
from flask_login import login_required
from flask import redirect, render_template, request, \
    jsonify, flash, abort, url_for
from werkzeug.security import generate_password_hash
from app_racine.utils import *
from flask_weasyprint import HTML, render_pdf
from sqlalchemy.sql import and_


@mosque_bp.before_request
def mosque_before_request():
    if current_user.is_authenticated and current_user.role == 'imam':
        session['mosque_name'] = Mosque.query.filter_by(user_account=current_user.id).first().nom


# @mosque_bp.route("/printTablePDF/<int:project_id>")
@mosque_bp.route("/printTablePDF")
@login_required
# def PrintTable(project_id):
def print_table():
    garants = Garant.query.filter(Garant.mosque_id == Mosque.query.filter_by(user_account=current_user.id).first().id)
    data = dict()
    if garants:
        data['items'] = [dict(
            id=familly.id,
            first_name=familly.nom,
            last_name=familly.prenom,
            date_nais=familly.date_nais.date(),
            tendancy=familly.Solde_finale,
            solde=familly.get_total_sum(),
            id_card_number=familly.id_card_num
        ) for familly in garants.all()]
        data['number_g'] = len(garants.all())
        data['wilaya'] = Wilaya.query.get(Mosque.query.filter_by(user_account=current_user.id).first().state).name
        data['date'] = datetime.utcnow().date()
        data['title']=Mosque.query.filter_by(user_account = current_user.id).first().nom
        data['total'] = sum([f.Solde_part_financiere for f in garants.all()])
    else:
        data = None
    print(data)
    html = render_template('mosque/list.html', data=data)
    return render_pdf(HTML(string=html))

    # temp = Mosque.query.filter_by(user_account=current_user.id).first()
    # if temp:
    #     return temp.PrintResume(project_id)
    # abort(404)


@mosque_bp.route('/garant/<int:_id>/print')
@login_required
def print_form(_id):
    garant = Garant.query.get(_id)
    html = render_template(
        'mosque/form_temp.html',
        garant=garant.data(),
        title=Mosque.query.filter_by(user_account=current_user.id).first().nom
    )
    return render_pdf(HTML(string=html))


# @mosque_bp.route('garant/<int:_id>/form')
# @login_required
# def PrintForm(_id):
#     garant = Garant.query.get(_id)
#     if garant:
#         return garant.print_form()
#     abort(404)


@mosque_bp.route('/mosque/dashboard', methods=['GET', 'POST'])
@login_required
def mosque_dashboard():
    mosque = Mosque.query.filter_by(user_account=current_user.id).first()
    if not mosque:
        abort(404)
    else:
        donation = DonateMosque.query.filter_by(mosque_id=mosque.id).all()
        donations = [user.user_id for user in donation] if donation else None
        return render_template(
            'mosque/mosque.html',
            donors=len(list(dict.fromkeys(donations))) if donations else 0,
            sum_donates=sum([don.amount for don in mosque.donors]),
            mosque=mosque.to_dict(),
            tendancy=Mosque.get_value(),
            nbre_inscrits=len(mosque.inscrits) if mosque.inscrits else 0
        )


@mosque_bp.route('/garants/new', methods=['GET', 'POST'])
@login_required
def register_garants():
    form = RegisterGarantForm()
    famille = PersonPerGarant()
    form.situation_sante.choices = [(x.id, x.label) for x in
                                    Critere.query.filter_by(category='الصحية').all()]
    form.situation_sociale.choices = [(x.id, x.label) for x in
                                      Critere.query.filter_by(
                                          category='الاجتماعية').all()]
    form.situation_familliale.choices = [(x.id, x.label) for x in
                                         Critere.query.filter_by(
                                             category='العائلية').all()]
    form.home_appliance.choices = [(x.id, x.label) for x in
                                   Critere.query.filter_by(category="الاجهزة الكهرومنزلية").all()]
    famille.situation.choices = [
        (state.id, state.label) for state in Critere.query.all()
    ]
    membre = Mosque.query.filter_by(user_account=current_user.id).first()
    if form.validate_on_submit():
        garant = Garant()
        garant.ccp = form.compte_ccp.data
        garant.id_card_num = form.card_id.data
        garant.id_card_release_date = form.release_date.data
        garant.id_card_release_authority = form.release_authority.data
        garant.cle_CCP = form.cle_ccp.data
        garant.prenom = form.prenom.data
        garant.nom = form.nom.data
        garant.address = form.address.data
        garant.phone_number = form.phone_number.data
        garant.date_nais = form.date_nais.data
        garant.num_extrait_nais = form.num_extrait_nais.data
        garant.mosque_id = membre.id
        liste = request.form.getlist('situation_sociale') + request.form.getlist(
            'situation_familliale') + request.form.getlist('situation_sante') + request.form.getlist('home_appliance')
        database.session.add(garant)
        database.session.commit()
        for case in liste:
            status = SituationGarant()
            status.garant_id = garant.id
            status.critere_id = int(case)
            database.session.add(status)
            database.session.commit()
        person = Personne()
        person.nom = famille.p_nom.data
        person.prenom = famille.p_prenom.data
        person.date_naissance = famille.p_date_nais.data
        person.relation_ship = famille.p_relation_ship.data
        person.garant_id = garant.id
        database.session.add(person)
        database.session.commit()
        # if famille.handicap.data:
        #     handicap = SituationPerson()
        #     handicap.personne_id = person.id
        #     handicap.critere_id = Critere.query.filter_by(label="اعاقة").first().id
        #     database.session.add(handicap)
        #     database.session.commit()
        if famille.cronic_desease.data:
            person.cronic_desease = famille.cronic_desease.data
            database.session.add(person)
            database.session.commit()
        if famille.situation.data:
            for state in request.form.getlist('situation'):
                _state = SituationPerson()
                _state.critere_id = int(state)
                _state.personne_id = person.id
                database.session.add(_state)
                database.session.commit()
        if int(request.form['max_clicks']) != 0:
            final_test = get_data_from_request(request, garant.id)
            if not final_test:
                flash('لقد تم تسجيل مكفول تم تسجيله من قبل ككفيل', 'danger')
                return redirect(url_for('mosque_bp.register_garants'))
        print(famille)
        count_points(garant, person)
        database.session.add(garant)
        database.session.commit()
        Mosque.tendance()
        flash("لقد تم اضـــــافة الفرد بنجاح", "success")
        return redirect(url_for('mosque_bp.register_garants'))
    else:
        print(form.errors)
        print(famille.errors)
    return render_template('mosque/register_G.html', famille=famille, form=form)


@mosque_bp.route('/api/situations', methods=['GET', 'POST'])
@login_required
def get_situation():
    response = [{'id': state.id, 'text': state.label} for state in Critere.query.all()]
    print(Critere.query.filter(Critere.label.like(f'%{request.args.get("search")}%')).all())
    if "search" in request.args:
        # print(f'search={get_display(arabic_reshaper.reshape(request.args.get("search")))}')
        response = [
            {'id': state.id, 'text': state.label} for state in
            Critere.query.filter(Critere.label.like(f'%{request.args.get("search")}%')).all()]
    return jsonify(response), 200


@mosque_bp.route("/donations/new", methods=['GET', 'POST'])
@login_required
def register_donation():
    form = RegisterNewDonationForm()
    form.project.choices = [(x.id, x.title) for x in Project.query.all()]
    membre = Mosque.query.filter_by(user_account=session['user_id']).first()
    if form.validate_on_submit():
        operation = DonateMosque()
        operation.mosque_id = membre.id
        user = User.query.filter_by(phone_number=form.phone_number.data).first()
        if not user:
            user = User()
            user.first_name = form.first_name.data
            user.last_name = form.last_name.data
            user.phone_number = form.phone_number.data
            user.role = 'donor'
            user.username = str(secrets.token_hex(8))
            password_hash = generate_password_hash(str(secrets.token_hex(8)), 'sha256')
            user.password = password_hash
            database.session.add(user)
            database.session.commit()
        operation.user_id = user.id
        operation.amount = form.montant.data
        database.session.add(operation)
        database.session.commit()
        flash("تمت الاضافـــة بنجاح", "success")
        return redirect(url_for('mosque_bp.register_donation'))
    return render_template("mosque/register_don.html", form=form)


@mosque_bp.route("/mosque/donations/<int:page>")
@login_required
def list_dons(page):
    mosque = Mosque.query.filter_by(user_account=session['user_id']).first()
    if not mosque:
        abort(404)
    else:
        donations = DonateMosque.query.filter_by(mosque_id=mosque.id)
        data = DonateMosque.to_collection_dict(
            query=donations,
            page=page,
            per_page=12,
            edit_endpoint=None,
            list_endpoint="mosque_bp.list_dons",
            delete_endpoint=None,
            view_endpoint=None,
            columns=["رقم العملية", 'التاريـــخ', 'المتبرع', 'المبلــغ']
        )

app_racine/templates/mosque/c_donnations.html
{% extends 'mosque.html' %}
{% block content %}
    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
            <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
                {% block header%}
                {% endblock header %}
                <div class="btn-toolbar mb-2 mb-md-0">
                        <a role="button" class="btn nav-link" href="{{ url_for('register_donnation') }}">تسجيـل عمليات</a>
                        <a role="button" class="btn nav-link" href="{{ url_for('list_dons') }}">عــرض قائمـة كل العمليات</a>
                </div>
            </div>
            
            <div class="row">
                <div class="col-md">
                    {% with messages = get_flashed_messages(with_categories=true) %}
                        {% if messages %}
                            {% for categorie , message in messages %}
                                <div class="alert alert-{{ categorie }}">
                                    {{ message }}
                                </div>
                            {% endfor %}
                        {% endif %}
                    {% endwith %}
                </div>
            </div>
            {% block block_for_donations %}
            {% endblock block_for_donations %}
    </main>
{% endblock content %}3000

app_racine/templates/mosque/c_donneurs.html
{%extends 'admin.html'%}

{% block content %}
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
	<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
		<h2 class="h2">المتبرعيـــن</h2>
		<div class="btn-toolbar mb-2 mb-md-0">
			<a class="btn nav-link" href="{{ url_for('register_donneurs') }}">إضــافة متبرع</a>
			<a class="btn nav-link" href="{{ url_for('list_donneurs') }}">عــرض قائمـة المتبرعيـــن</a>
		</div>
	</div>
	<div class="row">
    	<div class="col-md">
			{% with messages = get_flashed_messages(with_categories=true) %}
				{% if messages %}
					{% for categorie , message in messages %}
						<div class="alert alert-{{ categorie }}">
							{{ message }}
						</div>
					{% endfor %}
				{% endif %}
			{% endwith %}
		</div>
	</div>

    {% block content_for_donneurs %}
    {% endblock content_for_donneurs %}        	
</main>
    
{%endblock content%}

app_racine/templates/mosque/list.html
<!DOCTYPE html>
<html lang="ar" dir="rtl">
    <head>
        <meta charset="UTF-8">
        <title> قائمة الاسر  المتعففة  المسجلة: مسجد {{ title }}</title>
        <link href="{{ url_for('static', filename='css/styles.css' )}}" rel="stylesheet" />
        <link rel="stylesheet" href="{{url_for('static', filename='bootstrap-rtl.css')}}">
        <style>
            #border-table{
                border: solid 1px #000000;
                text-align: center;
                width: 100%;
            }

            @font-face {
              font-family: Amiri_font;
              src: url("{{ url_for('static', filename='fonts/AmiriRegular.ttf') }}");
            }
            @page {
                margin: 1cm;
                size: A4 landscape;
            }
            body{
                font-family: Amiri_font;
            }
        </style>
    </head>
    <body>
    <table style="width: 100%">
        <tr>
            <td>
                <img style="width: 30%;height: 30%;" src="{{ url_for('static',filename='image/logo_2.png') }}"></td>
            <td style="text-align: center;">
                <h2> قائمة الاسر  المتعففة  المسجلة</h2>
                <h3 >مسجــد {{ data['title'] }}</h3></td>
            <td></td>
        </tr>
    </table>
    <br>
    <table>
        <tr>
            <td>الولايـــة: </td>
            <td>{{ data['wilaya'] }} </td>
        </tr>
        <tr>
            <td>التاريـــخ: </td>
            <td>{{ data['date'] }} </td>
        </tr>
    </table>

    <table id="border-table">
        <tr>
            <td style="border: solid 1px #000000">الرقـم</td>
            <td style="border: solid 1px #000000">الاسـم و اللقـب</td>
            <td style="border: solid 1px #000000">ت.الميـلاد</td>
            <td style="border: solid 1px #000000">عدد الأسـهم</td>
            <td style="border: solid 1px #000000">القيمة (د.ج)</td>
            <td style="border: solid 1px #000000">بطاقـة الهويـة</td>
            <td style="border: solid 1px #000000">الإمضاء أو البصمـة</td>
        </tr>
        {% if data %}
            {% for foo in data['items'] %}
                <tr>
                    <td style="border: solid 1px #000000">{{ foo['id'] }}</td>
                    <td style="border: solid 1px #000000">{{ foo['last_name'] }} {{ foo['first_name'] }}</td>
                    <td style="border: solid 1px #000000">{{ foo['date_nais'] }}</td>
                    <td style="border: solid 1px #000000">{{ foo['tendancy'] }}</td>
                    <td style="border: solid 1px #000000">{{ "{:,.2f}".format(foo['solde']) }}</td>
                    <td style="border: solid 1px #000000">{{ foo['id_card_number'] }}</td>
                    <td style="border: solid 1px #000000"></td>
                </tr>
            {% endfor %}
        {% else %}
            <tr>
                <td colspan="7" style="border: solid 1px #000000" >القائمــة فارغة</td>
            </tr>
        {% endif %}
    </table>
    <br>
    <table style="width: 30%">
        <tr>
            <td>عدد المستفيـدين: </td>
            <td>{{ data['number_g'] }}</td>
        </tr>
        <tr>
            <td>المبلغ الإجمالي (د.ج): </td>
            <td>{{ "{:,.2f}".format(data['total']) }}</td>
        </tr>
    </table>
    <table style="width: 100%;">
        <tr>
            <td colspan="5"></td>
            <td colspan="2" style="text-align: center;">الإمضـاء و الختم</td>
        </tr>

    </table>


    </body>
</html>

app_racine/templates/mosque/list_D.html
{% extends 'c_donneurs.html' %}

{% block content_for_donneurs %}

	<!--champs pour la recherche avec saisie automatique-->
	{%if content['data'] %}
		<table class="table table-bordered table-hover">
			<thead>
				<tr>
					{% with columns = content['columns'] %}
						{% if columns %}
							{% for colonne in columns %}
								<th>{{colonne}}</th>
							{% endfor %}
						{% endif %}
					{% endwith %}
				</tr>
			</thead>
			<tbody>
				{% for line in content['data'] %}
				<tr>
					<td>{{line.id}}</td>
					<td>{{line.nom}}</td>
					<td>{{line.prenom}}</td>
					<td>{{line.adresse}}</td>
					<td>{{line.num_tele}}</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
	{% else %}
		<div class="alert alert-info text-center">
			<span>لم يتم إضافــة أي متبــــــــرع . </span>
		</div>
	
	{% endif %}

{% endblock content_for_donneurs %}
{% block scripts %}
	<script>
		$(document).ready( function () {
			$('#ui-table').DataTable({
				"bPaginate": false,
				"fixedColumns":   true,
				"info":     false,
				"language": {
					"url": "{{url_for('static', filename='DataTables/Arabic.json')}}"
				}
			});
		});
	</script>
{% endblock scripts %}

app_racine/templates/mosque/list_dons.html
{% extends './includes/mosque_layout.html' %}

{% block mosque_content %}
	<div class="container">
		<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
			{% if session['mosque_name'] %}
				<h1 class="h2">مسجـــد {{  session['mosque_name'] }} </h1>
			{% endif %}
            {#
            <div class="btn-toolbar mb-2 mb-md-0">
                <a target="_blank" class="btn btn-outline-primary nav-link" href="#">طبــــع القائمـة</a>
            </div>
            #}
		</div>
		<div class="row justify-content-center">
			<div class="col-md">
				<div class="card shadow-lg border-0 rounded-lg mt-5">
					<div class="card-header">
						<div class="row">
							<div class="col-md">
								<h3 class="h3">
									المتبرعيــن و عمليات التبرع
								</h3>
							</div>
							<div class="col-md text-right">
								<a class="btn btn-outline-primary" href="{{ url_for('mosque_bp.register_donation') }}">
									<i class="fa fa-plus"></i></a>
							</div>
						</div>
					</div>
					{% include "includes/ui-table.html" %}
				</div>
			</div>
		</div>
	</div>
{% endblock mosque_content %}
{% block scripts %}
    <script>
        $(document).ready( function () {
            $('#ui-table').DataTable({
                "bPaginate": false,
                "fixedColumns":   true,
                "info":     false,
                "language": {
                    "url": "{{url_for('static', filename='DataTables/Arabic.json')}}"
                }
            });
        });
    </script>
{% endblock scripts %}

app_racine/templates/mosque/list_garants.html
{% extends './includes/mosque_layout.html' %}
{% block stylesheets %}
	<link rel="stylesheet" href="{{ url_for('static', filename='css/select2.min.css') }}">
{% endblock stylesheets %}
{% block mosque_content %}
	<div class="container-fluid">
		<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
			{% if session['mosque_name'] %}
				<h1 class="h2">مسجـــد {{  session['mosque_name'] }} </h1>
			{% endif %}
			{%if results %}
				<div class="btn-toolbar mb-2 mb-md-0">
{#					{% if 'project_id' in session and session['project_id'] != -1 %}#}
						<a target="_blank" class="btn btn-outline-primary nav-link" href="{{ url_for('mosque_bp.print_table') }}">طبــــع القائمـة</a>
{#					{% else %}#}
{#						<a target="_blank" class="btn btn-outline-primary nav-link" href="{{ url_for('mosque_bp.PrintTable',#}
{#																				project_id = -1) }}">طبــــع القائمـة</a>#}
{#					{% endif %}#}

				</div>
			{% endif %}
		</div>
{#		<div class="row justify-content-right">#}
{#			<div class="col-md">#}
{#				<form method="post" action="{{ url_for('mosque_bp.list_garants', page = 1) }}">#}
{#					{{ form.hidden_tag() }}#}
{#					<div class="form-row">#}
{#						<div class="col-md">#}
{#							{{ form.projects.label(class="form-control-label") }}#}
{#							{% if form.projects.errors %}#}
{#								{{ form.projects(class="select-project form-control form-control-md", onchange="form.submit()") }}#}
{#								{% for error in form.projects.errors %}#}
{#									<div class="alert alert-danger">#}
{#										{{error}}#}
{#									</div>#}
{#								{% endfor %}#}
{#							{% else %}#}
{#								{{ form.projects(class="select-project form-control form-control-md", onchange="form.submit()") }}#}
{#							{% endif %}#}
{#						</div>#}
{#					</div>#}
{#				</form>#}
{#			</div>#}
{#		</div>#}
		<div class="row justify-content-center">
			<div class="col-md">
				<div class="card shadow-lg border-0 rounded-lg mt-5">
					<div class="card-header">
						<div class="row">
							<div class="col-md">
								<h3 class="h3">
									المحتاجيــن
								</h3>
							</div>
							<div class="col-md text-right">
								<a class="btn btn-outline-primary" href="{{ url_for('mosque_bp.register_garants') }}">
									<i class="fa fa-plus"></i></a>
							</div>
						</div>
					</div>
					{% include "includes/ui-table.html" %}
				</div>
			</div>
		</div>
	</div>
{% endblock mosque_content %}

{% block scripts %}
	<script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>
	<script src="{{ url_for('static', filename='js/select2.min.js') }}"></script>
	<script>
		$(document).ready( function () {
			$('.select-project').select2();
			$('#ui-table').DataTable({
				"bPaginate": false,
				"fixedColumns":   true,
				"info":     false,
				"language": {
					"url": "{{url_for('static', filename='DataTables/Arabic.json')}}"
				}
			});
		});
	</script>
{% endblock scripts %}

app_racine/templates/mosque/mosque.html
{%extends './includes/mosque_layout.html'%}

{% block mosque_content %}
	<div class="container-fluid">
		{% with messages = get_flashed_messages(with_categories=true) %}
			{% if messages %}
				{% for category , message in messages %}
					<div class="alert alert-{{category}} alert-dismissible" role="alert">
						{{ message }}
						<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
								aria-hidden="true" class="text-left">&times;</span></button>
					</div>
				{% endfor %}
			{% endif %}
		{% endwith %}
		<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
			{% if mosque %}
				<h1 class="h1">مسجـــد {{ mosque['name'] }} </h1>
			{% else %}
				<h1 class="h1">لوحــة التحكـــم</h1>
			{% endif %}
		</div>
		<div class="row justify-content-center">
			<div class="col-md-3">
				<div class="card">
					<div class="card-header">
						<h5 class="h5">
							عـدد المسجليـن
						</h5>
					</div>
					<div class="text-right card-body">
						<h1 class="h1">

							{{ nbre_inscrits }}
						</h1>
					</div>
				</div>
			</div>
			<div class="col-md-3">
				<div class="card">
					<div class="card-header">
						<h5 class="h5">
							الميــزان المالي
						</h5>
					</div>
					<div class="text-right card-body">
						<h1 class="h1">
							{{ "{:,.2f}".format(sum_donates) }} د.ج
						</h1>
					</div>
				</div>
			</div>
			<div class="col-md-3">
				<div class="card">
					<div class="card-header">
						<h5 class="h5">
							عــدد المتبرعيــــن
						</h5>
					</div>
					<div class="text-right card-body">
						<h1 class="h1">
							{{donors}}
						</h1>
					</div>
				</div>
			</div>
			<div class="col-md-3">
				<div class="card">
					<div class="card-header">
						<h5 class="h5">
							قيمـــة السهــم
						</h5>
					</div>
					<div class="text-right card-body">
						<h1 class="h1">
							{{ "{:,.2f}".format(tendancy)}} د.ج
						</h1>
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock mosque_content %}

app_racine/templates/mosque/register_D.html
{% extends 'c_donneurs.html' %}
{% block content_for_donneurs %}
        <form method="POST">
                {{ form_m.hidden_tag() }}
                <fieldset class="form-group">
                    <div class="form-group">
                        {{ form_m.nom.label(class="form=control-label") }}
                        {% if form_m.nom.errors %}
                            {{ form_m.nom(class="form-control from-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form_m.nom.errors %}                            
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form_m.nom(class="form-control from-control-md") }}
                        {% endif %}
                    </div>
                    <div class="form-group">
                        {{ form_m.prenom.label(class="form=control-label") }}
                        {% if form_m.prenom.errors %}
                            {{ form_m.prenom(class="form-control from-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form_m.prenom.errors %}                           
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form_m.prenom(class="form-control from-control-lg") }}
                        {% endif %}
                    </div>
                    <div class="form-group">
                        {{ form_m.adresse.label(class="form=control-label") }}
                        {{ form_m.adresse(class="form-control from-control-lg") }}
                    </div>
                    <div class="form-group">
                        {{ form_m.num_tele.label(class="form=control-label") }}
                        {% if form_m.num_tele.errors %}
                            {{ form_m.num_tele(class="form-control from-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form_m.num_tele.errors %}                          
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form_m.num_tele(class="form-control from-control-lg") }}
                        {% endif %}
                    </div>
                    <div class="form-group">
                        {{ form_m.password.label(class="form=control-label") }}
                        {% if form_m.password.errors %}
                            {{ form_m.password(class="form-control from-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form_m.password.errors %}
                                   <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form_m.password(class="form-control from-control-lg") }}
                        {% endif %}
                    </div>
                    <div class="form-group">
                        {{ form_m.confirm_password.label(class="form=control-label") }}
                        {% if form_m.confirm_password.errors %}
                            {{ form_m.confirm_password(class="form-control from-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form_m.confirm_password.errors %}
                                   <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form_m.confirm_password(class="form-control from-control-lg") }}
                        {% endif %}
                    </div>
                </fieldset>
                    <div class="form-group">
                        {{ form_m.submit(class="btn btn-outline-info") }}
                    </div>
            </form> 
{% endblock content_for_donneurs %}